version: '2'
services:
  web:
    build: .
    ports:
    - 80:80
    restart: always
    env_file:
      - ./production.env
    links:
      - mongo:mongo

  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - /var/lib/mongo/data
