default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV['DB_USERNAME'] %>
  host:     <%= ENV['DB_HOST'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  database: <%= ENV['DB_NAME'] %>
  pool:     10

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
