version: '3'
services:
  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./bin/data/mysql:/var/lib/mysql
  app:
    build: .
    env_file:
      - .env
    entrypoint:
      - ./bin/www/init.sh
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    depends_on:
      - db
